# Hexo Configuration
title: Kang Blog
deploy:
  type: git
  repo: https://github.com/TBodyAltra/Kang.Blog.git
  branch: gh-pages

theme: butterfly
url: https://tbodyaltra.github.io/Kang.Blog

author: TBodyAltra
social:
  github: https://github.com/TBodyAltra

post_asset_folder: true

mathjax:
  enable: true
  path: ""
  per_page: 10
  order_by: -date
index_generator:
  path: ''
  per_page: 10
  order_by: -date
